name: Flake8 Check

on:
  push:
    branches:
      - Mattis  # ajustez en fonction de la branche

jobs:
  flake8:
    name: Check Python code with Flake8
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.12.0  # ajustez en fonction de la version de Python

    - name: Show Python version
      run: python --version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8

    - name: Run Flake8
      run: |
        flake8 .
